### ISSUE TITLE
Hi, eckhaus! what is the binary file lcs and how to use it?

### ISSUE THREAD

**Issue by ludlows** [eckhaus/Thesis#1]
I am doing research to find the binding site in PDB file.
Can the lcs file help me to achieve my goal?
How to use it?
and What is the source code you compiled to get the binary file lcs?

Thanks, have a nice day!

**Comment by eckhaus** [comment]
Hi ludlows,

I actually committed the binary only by accident. It's the compiled source code of [LIGSITEcs](http://projects.biotec.tu-dresden.de/pocket/). LIGSITEcs is a protein-ligand (small molecules, not PPI) binding site prediction algorithm, so I guess that does what you want. If I were you, I'd opt for some other algorithm though. The installation process is described in the link, but there are a few issues with BALL v.1.1.1 library. Segfaults in the PDB parser, missing includes in headers, stuff like that :D. In the end, I've got it running somehow - here are my (possibly quite incomplete) notes on what I did, maybe they'll help you: [notes.pdf](https://github.com/eckhaus/Thesis/files/876417/notes.pdf)

That said, there are many algorithms out there that have both better predictive performance and are more stable (and readily available). Take a look at some of the reviews on PubMed ([Dukka](https://www.ncbi.nlm.nih.gov/pubmed/24688745/), [Chen et al.](https://www.ncbi.nlm.nih.gov/pubmed/21565696), [Roche et al.](https://www.ncbi.nlm.nih.gov/pubmed/26694353)). Many of the algorithms mentioned there are implemented as prediction servers (COACH, MetaPocker 2.0) and/or have binaries available for download (for example [PASS](http://www.ccl.net/cca/software/UNIX/pass/overview.html), Concavity, fpocket, ghecom, bSiteFinder, lise, sitehound, ... ). So unless you need to work with LigsiteCS specifically, I think you're better off using one of those.

Good luck with your research!

Robert

**Comment by ludlows** [comment]
Thanks for your very very very warm responses!

Actually, I am re-implementing an algorithm which used ligsite(csc) as a feature of voxel then predicted the properties by deep neural networks from the features. So ligsite is the first step for me.

According to your description, I think you are an expert in Bioinformatics. When I finished this Deep Neural Networks, I can change ligsite method into PASS method you mentioned and see the different performance between them.

I think you can contribute the [BALL-Project](https://github.com/BALL-Project/ball) if you have time. :+1: 

By the way, I have followed you! 

Have a nice day! Robert

ludlows

**Comment by ludlows** [comment]
Robert, this URL (https://abibuilder.informatik.unituebingen.de/archive/ball/BALL/stable/v1.1.1/) has been broken. Do you have the source code?

**Comment by eckhaus** [comment]
Glad I could help. Try downloading v.1.1.1 from https://abibuilder.informatik.uni-tuebingen.de/archive/ball/BALL/stable/

Feel free to mail me if you have any further questions.

**Comment by ludlows** [comment]
Thank you!
I have downloaded and compiled the source code!
Have a nice day!
